### ISSUE TITLE
RowParser single column parsers should return RowParsers

### ISSUE THREAD

**Issue by msiebert** [lucidsoftware/relate#50]
example:
`RowParser.long` returns `(SqlRow) => Long`, which isn't compatible with the new `.as[A]` syntax. It should return `RowParser[Long]` instead.

**Comment by gregghz** [comment]
`RowParser(RowParser.long("col"))`

It's not already a `RowParser` because making it implicit generally doesn't make sense. You have to globally (ish) say what column name maps to a `Long` so any call to `as[Long]` will also demand a single column name. If you want this in your application, I suggest creating it yourself.

**Comment by msiebert** [comment]
That's what I've done locally and I don't want to make an implicit val for reading `Long`s. I just think that it makes more sense to do:
```scala
implicit val longParser = RowParser.long("column")
```
than
```scala
implicit val longParser = RowParser(RowParser.long("column"))
```

**Comment by gregghz** [comment]
I don't follow.

>I don't want to make an implicit val for reading Longs

And then you make an implicit val for reading longs?

**Comment by msiebert** [comment]
Sorry, I meant that I don't want to make it an implicit val in the RowParser object. I just wanted to put the invocation of RowParser.apply in the RowParser.long function. I just created this issue so that I'd remember to do it and make a pull request later.

**Comment by gregghz** [comment]
makes sense. I've created a PR: https://github.com/lucidsoftware/relate/pull/51
